name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Gather code coverage
      run: xcrun llvm-cov export -format="lcov" .build/debug/SwiftMockPackageTests.xctest/Contents/MacOS/SwiftMockPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.1.0
      with:
        fail_ci_if_error: true
        files: ./coverage_report.lcov
        verbose: true
